# Generated by Django 3.2.5 on 2022-03-02 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('seller_name', models.CharField(max_length=100, verbose_name='Seller Name')),
                ('seller_address', models.CharField(max_length=200, verbose_name='Seller Addresss')),
                ('seller_mobile', models.BigIntegerField(verbose_name='Seller Mobile')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='Buyer Name')),
                ('buyer_address', models.CharField(max_length=200, verbose_name='Buyer Address')),
                ('buyer_mobile', models.BigIntegerField(verbose_name='Buyer Mobile')),
            ],
            options={
                'ordering': ('-invoice_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Item Name')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
        ),
    ]
